/*
 * This Java source file was generated by the Gradle 'init' task.
*Laura Nohemi Morales Pablo
 */
import org.junit.Test;
/**
 * @author Laura Morales
 * Hola esto es mi primer prueba
 */
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
